# Generated by Django 5.0.6 on 2025-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0009_remove_carousel_size_alter_carousel_nfc_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=True, verbose_name='Только чтение с постов наполнения')),
                ('use_weight_management', models.BooleanField(default=False, verbose_name='Использовать коррекцию веса')),
                ('use_common_correction', models.BooleanField(default=False, verbose_name='Использовать общее значение коррекции веса')),
                ('weight_correction_value', models.FloatField(blank=True, null=True, verbose_name='Значение корректировки веса')),
                ('post_1_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 1 поста')),
                ('post_2_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 2 поста')),
                ('post_3_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 3 поста')),
                ('post_4_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 4 поста')),
                ('post_5_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 5 поста')),
                ('post_6_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 6 поста')),
                ('post_7_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 7 поста')),
                ('post_8_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 8 поста')),
                ('post_9_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 9 поста')),
                ('post_10_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 10 поста')),
                ('post_11_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 11 поста')),
                ('post_12_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 12 поста')),
                ('post_13_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 13 поста')),
                ('post_14_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 14 поста')),
                ('post_15_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 15 поста')),
                ('post_16_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 16 поста')),
                ('post_17_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 17 поста')),
                ('post_18_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 18 поста')),
                ('post_19_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 19 поста')),
                ('post_20_correction', models.FloatField(blank=True, null=True, verbose_name='Корректор для 20 поста')),
            ],
            options={
                'verbose_name': 'Настройки карусели',
                'verbose_name_plural': 'Настройки карусели',
            },
        ),
    ]
