# Generated by Django 5.0.6 on 2025-03-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0010_carouselsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_10_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 10 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_11_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 11 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_12_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 12 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_13_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 13 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_14_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 14 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_15_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 15 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_16_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 16 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_17_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 17 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_18_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 18 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_19_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 19 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_1_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 1 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_20_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 20 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_2_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 2 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_3_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 3 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_4_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 4 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_5_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 5 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_6_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 6 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_7_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 7 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_8_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 8 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='post_9_correction',
            field=models.FloatField(default=0.0, verbose_name='Корректор для 9 поста'),
        ),
        migrations.AlterField(
            model_name='carouselsettings',
            name='weight_correction_value',
            field=models.FloatField(default=0.0, verbose_name='Значение корректировки веса'),
        ),
    ]
