# Generated by Django 5.0.6 on 2025-03-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0011_alter_carouselsettings_post_10_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carousel_number',
            field=models.IntegerField(default=1, verbose_name='Номер карусели наполнения'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='size',
            field=models.IntegerField(choices=[(5, 5), (12, 12), (27, 27), (50, 50)], default=50, verbose_name='Объём'),
        ),
    ]
