# Generated by Django 5.1.4 on 2025-04-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0013_balloonsloadingbatch_amount_of_ttn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='CarouselSettings',
        ),
    ]
