# Generated by Django 5.0.6 on 2025-04-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0013_balloonsloadingbatch_amount_of_ttn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(default='', max_length=10, verbose_name='Номер версии')),
                ('apk_file', models.FileField(upload_to='apk/', verbose_name='APK файл')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Версия мобильного приложения',
                'verbose_name_plural': 'Версии мобильного приложения',
                'ordering': ['-update_date'],
            },
        ),
    ]
